project:
  type: book
  output-dir: docs

book:
  title: "rsbook"
  author: "Jane Doe"
  date: "26/01/2023"
  chapters:
    - index.qmd
    - Chapter1.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

